version: '3.7'
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - "9081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true

  postgres:
    hostname: postgres-db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - my-db:/var/lib/postgresql

volumes:
  my-db: