version: '3.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    ports:
      - "8181:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    depends_on:
       postgres_keycloak:
         condition: service_healthy
    networks:
        - keycloak_dev_network

  postgres_keycloak:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - '5436:5432'
    networks:
      - keycloak_dev_network

volumes:
  pgdata_keycloak:
networks:
  keycloak_dev_network:
    driver: bridge

#  postgres:
#    hostname: postgres-db
#    image: postgres:latest
#    environment:
#      - POSTGRES_PASSWORD=password
#    ports:
#      - '5432:5432'
#    volumes:
#      - my-db:/var/lib/postgresql
#
#volumes:
#  my-db: